### ISSUE TITLE
against tos

### ISSUE THREAD

**Issue by nerdthatnoonelikes** [nickbotclient/nickbotclient#3]
mate this is against tos

**Comment by ABotDev** [comment]
Make screenshot because i know its not because discord maked it them self some years ago

**Comment by ABotDev** [comment]
And where does it say that in the tos

**Comment by nerdthatnoonelikes** [comment]
![image](https://user-images.githubusercontent.com/33642056/92666310-82ced800-f2ce-11ea-8959-900bded3bf85.png)

**Comment by nickbotclient** [comment]
did a discord moderator said that?

**Comment by Zaid-maker** [comment]
some dickheads say that

**Comment by nickbotclient** [comment]
i don't think its abuse because you can't do much griefing
and you can do the same things as what you can build in a bot

**Comment by Zaid-maker** [comment]
yeah, this thread is closed now.
